/* Copyright (c) 2025 VISO TRUST */
package com.visotrust.viso.visomcpserver.model.webhook;

public enum WebhookEventType {
    ASSESSMENT_COMPLETED,
    ASSESSMENT_RECERTIFICATION_COMPLETED,
    ASSESSMENT_ARTIFACT_UPDATE_COMPLETED,
    DOCS_ONLY_ARTIFACT_UPDATE_COMPLETED,
    ASSESSMENT_REMINDER,
    ASSESSMENT_CANCELLED,
    ASSESSMENT_CANCELLED_BY_AUDITOR,
    ASSESSMENT_AUTOMATICALLY_CANCELLED,
    UPCOMING_RECERTIFICATION,
    RELATIONSHIP_OVERDUE,
    ARTIFACT_EXPIRING,
    ARTIFACT_EXPIRED
}
