blank_issues_enabled: false
contact_links:
  - name: VISO TRUST Support
    url: https://support.visotrust.com/
    about: Please contact VISO TRUST support for questions related to your account or service.
