/* Copyright (c) 2025 VISO TRUST */
package com.visotrust.viso.visomcpserver.model.auditlog;

public enum UserAuditLogType {
    USER_LOGGED_IN,
    USER_LOGGED_OUT,
    USER_FIRST_LOG_IN,
    EXISTING_USER_FIRST_LOG_IN,
    NEW_USER_FIRST_LOG_IN,
    USER_CREATED,
    USER_UPDATED,
    USER_SUBSCRIBED,
    USER_UNSUBSCRIBED,
    USER_DEFAULT_SUBSCRIBER_ADDED,
    USER_DEFAULT_SUBSCRIBER_REMOVED,
    USER_UPLOADED_ARTIFACT,
    USER_DOWNLOADED_ARTIFACT,
    USER_EXPORTED_ARTIFACT
}
